backend:
  name: github
  repo: BDEGUARDO/beatrizdeguardo-nuevo
  branch: main
  auth_type: token

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "cuadros"
    label: "Cuadros"
    folder: "content/cuadros"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Técnica", name: "tecnica", widget: "string" }
      - { label: "Medidas", name: "medidas", widget: "string" }
      - { label: "Descripción", name: "descripcion", widget: "text" }
      - { label: "Categoría", name: "categoria", widget: "select", options: ["Figurativo", "Abstracto", "Étnico", "Figurativo etérico"] }
      - { label: "Imagen", name: "imagen", widget: "image" }