backend:
  name: github
  repo: BDEGUARDO/beatrizdeguardo-nuevo
  branch: main
  auth_type: "token"


media_folder: "assets/images"
public_folder: "/assets/images"

collections:
  - name: "abstracto"
    label: "Abstracto"
    folder: "collections/abstracto"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Técnica", name: "tecnica", widget: "string" }
      - { label: "Medidas", name: "medidas", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }

  - name: "figurativo"
    label: "Figurativo"
    folder: "collections/figurativo"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Técnica", name: "tecnica", widget: "string" }
      - { label: "Medidas", name: "medidas", widget: "string" }
      - { label: "Descripción", name: "body", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
